<?php

namespace NAO\MapBundle\Repository;

/**
 * ObservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObservationRepository extends \Doctrine\ORM\EntityRepository
{
  public function findMarkers() {

    $query = $this->_em->createQuery('SELECT o.title, o.lat, o.lng FROM NAOMapBundle:Observation o');
    $results = $query->getArrayResult();

    return $results;
  }
}
