nao_map_homepage:
    path:     /
    defaults: { _controller: NAOMapBundle:Default:index }

nao_map_addpage:
    path:    /add
    defaults: { _controller: NAOMapBundle:Default:add }

nao_map_jsonpage:
    path:    /obsjson
    defaults: { _controller: NAOMapBundle:Default:observations }
